const admin = require('firebase-admin/app');
const { cert } = require('firebase-admin/app');
const { getFirestore } = require('firebase-admin/firestore');
require('dotenv').config({ path: '.env.local' });

const serviceAccount = {
  projectId: process.env.FIREBASE_ADMIN_PROJECT_ID,
  clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL,
  privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY.replace(/\\n/g, '\n'),
};

admin.initializeApp({
  credential: cert(serviceAccount),
});

const db = getFirestore();

const COURSES = [
  {
    name: 'Bachelor of Science in Computer Science',
    universityName: 'MIT',
    country: 'US',
    field: 'Computer Science & IT',
    level: 'undergraduate',
    tuitionFee: 60000,
    currency: 'USD',
    durationMonths: 48,
    intakes: ['Sep 2024', 'Jan 2025'],
    eligibility: { minGPA: 3.5, requiredTests: ['SAT'] },
    commissionRate: 2.5,
    qsRanking: 1,
  },
  {
    name: 'Master of Science in Computer Science',
    universityName: 'University of British Columbia',
    country: 'CA',
    field: 'Computer Science & IT',
    level: 'postgraduate',
    tuitionFee: 22000,
    currency: 'CAD',
    durationMonths: 24,
    intakes: ['Sep 2025', 'Jan 2026'],
    eligibility: { minGPA: 3.2, requiredTests: ['IELTS', 'GRE'] },
    commissionRate: 2.5,
    qsRanking: 47,
  },
  {
    name: 'Bachelor of Information Technology',
    universityName: 'University of Queensland',
    country: 'AU',
    field: 'Computer Science & IT',
    level: 'undergraduate',
    tuitionFee: 32000,
    currency: 'AUD',
    durationMonths: 36,
    intakes: ['Feb 2025', 'Jul 2025'],
    eligibility: { minGPA: 3.0, requiredTests: ['IELTS'] },
    commissionRate: 2.0,
    qsRanking: 55,
  },
  {
    name: 'MBA in Finance',
    universityName: 'London Business School',
    country: 'GB',
    field: 'Business & Management',
    level: 'postgraduate',
    tuitionFee: 55000,
    currency: 'GBP',
    durationMonths: 18,
    intakes: ['Sep 2025'],
    eligibility: { minGPA: 3.2, requiredTests: ['GMAT', 'IELTS'] },
    commissionRate: 3.0,
    qsRanking: 6,
  },
  {
    name: 'Master of Public Health',
    universityName: 'Johns Hopkins University',
    country: 'US',
    field: 'Medicine & Health',
    level: 'postgraduate',
    tuitionFee: 58000,
    currency: 'USD',
    durationMonths: 24,
    intakes: ['Sep 2025'],
    eligibility: { minGPA: 3.0, requiredTests: ['GRE', 'TOEFL'] },
    commissionRate: 2.5,
    qsRanking: 3,
  },
  {
    name: 'Bachelor of Nursing',
    universityName: 'University of Auckland',
    country: 'NZ',
    field: 'Medicine & Health',
    level: 'undergraduate',
    tuitionFee: 28000,
    currency: 'NZD',
    durationMonths: 36,
    intakes: ['Feb 2025', 'Jul 2025'],
    eligibility: { minGPA: 2.8, requiredTests: ['IELTS'] },
    commissionRate: 2.0,
    qsRanking: 85,
  },
  {
    name: 'Master of Artificial Intelligence',
    universityName: 'Technical University of Munich',
    country: 'DE',
    field: 'Computer Science & IT',
    level: 'postgraduate',
    tuitionFee: 5000,
    currency: 'EUR',
    durationMonths: 24,
    intakes: ['Oct 2025'],
    eligibility: { minGPA: 3.3, requiredTests: ['IELTS', 'GRE'] },
    commissionRate: 1.5,
    qsRanking: 50,
  },
  {
    name: 'Bachelor of Business Administration',
    universityName: 'Ryerson University',
    country: 'CA',
    field: 'Business & Management',
    level: 'undergraduate',
    tuitionFee: 18000,
    currency: 'CAD',
    durationMonths: 48,
    intakes: ['Sep 2025', 'Jan 2026'],
    eligibility: { minGPA: 2.8, requiredTests: ['IELTS'] },
    commissionRate: 2.0,
    qsRanking: 401,
  },
  {
    name: 'Master of Engineering Management',
    universityName: 'Monash University',
    country: 'AU',
    field: 'Engineering',
    level: 'postgraduate',
    tuitionFee: 38000,
    currency: 'AUD',
    durationMonths: 24,
    intakes: ['Feb 2025', 'Jul 2025'],
    eligibility: { minGPA: 3.0, requiredTests: ['IELTS'] },
    commissionRate: 2.5,
    qsRanking: 57,
  },
  {
    name: 'Bachelor of Psychology',
    universityName: 'University of Edinburgh',
    country: 'GB',
    field: 'Social Sciences',
    level: 'undergraduate',
    tuitionFee: 22000,
    currency: 'GBP',
    durationMonths: 48,
    intakes: ['Sep 2025'],
    eligibility: { minGPA: 3.0, requiredTests: ['IELTS'] },
    commissionRate: 2.0,
    qsRanking: 22,
  },
  {
    name: 'Master of Finance',
    universityName: 'University of Toronto',
    country: 'CA',
    field: 'Business & Management',
    level: 'postgraduate',
    tuitionFee: 42000,
    currency: 'CAD',
    durationMonths: 12,
    intakes: ['Sep 2025'],
    eligibility: { minGPA: 3.3, requiredTests: ['GMAT', 'IELTS'] },
    commissionRate: 3.0,
    qsRanking: 25,
  },
  {
    name: 'Master of Business Administration',
    universityName: 'Harvard Business School',
    country: 'US',
    field: 'Business & Management',
    level: 'postgraduate',
    tuitionFee: 75000,
    currency: 'USD',
    durationMonths: 24,
    intakes: ['Sep 2024', 'Jan 2025'],
    eligibility: { minGPA: 3.0, requiredTests: ['GMAT'] },
    commissionRate: 3.0,
    qsRanking: 2,
  },
  {
    name: 'Bachelor of Engineering',
    universityName: 'University of Toronto',
    country: 'CA',
    field: 'Engineering',
    level: 'undergraduate',
    tuitionFee: 20000,
    currency: 'CAD',
    durationMonths: 48,
    intakes: ['Sep 2024', 'Jan 2025'],
    eligibility: { minGPA: 3.2, requiredTests: ['IELTS'] },
    commissionRate: 2.0,
    qsRanking: 25,
  },
  {
    name: 'Master of Science in Data Science',
    universityName: 'University of Melbourne',
    country: 'AU',
    field: 'Computer Science & IT',
    level: 'postgraduate',
    tuitionFee: 45000,
    currency: 'AUD',
    durationMonths: 24,
    intakes: ['Feb 2025', 'Jul 2025'],
    eligibility: { minGPA: 3.3, requiredTests: ['IELTS', 'GRE'] },
    commissionRate: 2.5,
    qsRanking: 37,
  },
  {
    name: 'Bachelor of Law',
    universityName: 'University of Oxford',
    country: 'GB',
    field: 'Law',
    level: 'undergraduate',
    tuitionFee: 35000,
    currency: 'GBP',
    durationMonths: 36,
    intakes: ['Sep 2024', 'Jan 2025'],
    eligibility: { minGPA: 3.7, requiredTests: ['IELTS'] },
    commissionRate: 2.5,
    qsRanking: 4,
  },
  {
    name: 'Master of Medicine',
    universityName: 'University of Cambridge',
    country: 'GB',
    field: 'Medicine & Health',
    level: 'postgraduate',
    tuitionFee: 40000,
    currency: 'GBP',
    durationMonths: 24,
    intakes: ['Jan 2025'],
    eligibility: { minGPA: 3.8, requiredTests: ['IELTS'] },
    commissionRate: 3.5,
    qsRanking: 2,
  },
  {
    name: 'Bachelor of Commerce',
    universityName: 'University of Sydney',
    country: 'AU',
    field: 'Business & Management',
    level: 'undergraduate',
    tuitionFee: 35000,
    currency: 'AUD',
    durationMonths: 48,
    intakes: ['Feb 2025', 'Jul 2025'],
    eligibility: { minGPA: 3.0, requiredTests: ['IELTS'] },
    commissionRate: 2.0,
    qsRanking: 50,
  },
  {
    name: 'Master of Architecture',
    universityName: 'ETH Zurich',
    country: 'DE',
    field: 'Architecture',
    level: 'postgraduate',
    tuitionFee: 15000,
    currency: 'CHF',
    durationMonths: 24,
    intakes: ['Sep 2024'],
    eligibility: { minGPA: 3.4, requiredTests: ['IELTS'] },
    commissionRate: 2.0,
    qsRanking: 10,
  },
];

async function seedCourses() {
  console.log('🌱 Starting course seed...');

  try {
    for (const course of COURSES) {
      const docRef = db.collection('courses').doc();
      await docRef.set(course);
      console.log(`✅ Added: ${course.name} (${course.universityName})`);
    }

    console.log('\n✨ Seeding complete! 8 courses added.');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding failed:', err);
    process.exit(1);
  }
}

seedCourses();
